var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var gameBoard=[[0,0,0],[0,0,0],[0,0,0]],turn=1,turns=0,winner=0,mode=0,record={p1:0,p2:0,ties:0},ls=window.localStorage,saveRecord=function(){ls.setItem("record",JSON.stringify(record))},loadRecord=function(){var a=JSON.parse(ls.getItem("record"));a&&(a=$jscomp.makeIterator([a.p1,a.p2,a.ties]),record.p1=a.next().value,record.p2=a.next().value,record.ties=a.next().value)},reset=function(){gameBoard=[[0,0,0],[0,0,0],[0,0,0]];turn=1;mode=winner=turns=0;refreshDisplay();modifyEventHandlers("");document.getElementById("board").classList.add("hidden");
var a=document.getElementById("turn");a.textContent="Play as...";var b=document.createElement("div");b.id="start-buttons";var c=document.createElement("button"),g=document.createElement("button"),l=document.createElement("button"),e=document.createElement("button");c.textContent="Human vs Human";c.setAttribute("onclick","mode=1;showBoard();refreshDisplay();modifyEventHandlers('getCellCoords(event)');");g.textContent="Human vs CPU";g.setAttribute("onclick","mode=2;showBoard();refreshDisplay();modifyEventHandlers('getCellCoords(event)')");
l.textContent="CPU vs Human";l.setAttribute("onclick","mode=3;showBoard();modifyEventHandlers('getCellCoords(event)');refreshDisplay();setTimeout(play,1000)");e.textContent="Spectate CPU vs CPU";e.setAttribute("onclick","mode=4;showBoard();modifyEventHandlers('');refreshDisplay();setTimeout(play,1000)");b.appendChild(c);b.appendChild(g);b.appendChild(l);b.appendChild(e);a.appendChild(b)},highlight=function(a,b){var c=Math.floor(Number(b.target.id)/3),g=Number(b.target.id)%3;a&&!gameBoard[c][g]&&4!==
mode?(2===mode&&1===turn||3===mode&&2===turn||1===mode)&&b.target.classList.add("hover"):a||(console.log("mouseoff"),b.target.classList.remove("hover"))},playSound=function(a){(new Audio(a)).play()},changeTurn=function(){1===turn?(playSound("x.webm"),turn=2):(playSound("o.webm"),turn=1);turns++},modifyEventHandlers=function(a){for(var b=document.getElementsByClassName("grid-item"),c=0;c<b.length;c++)b[c].setAttribute("onclick",a)},showBoard=function(){document.getElementById("board").classList.remove("hidden")},
refreshDisplay=function(){1===winner?(record.p1++,document.getElementById("turn").textContent="Player 1 wins",document.getElementsByTagName("html")[0].style.backgroundColor="#778899",document.getElementById("board").style.backgroundColor="#2196F3"):2===winner?(record.p2++,document.getElementById("turn").textContent="Player 2 wins",document.getElementsByTagName("html")[0].style.backgroundColor="#aa8484",document.getElementById("board").style.backgroundColor="#f32121"):-1===winner?(record.ties++,document.getElementById("turn").textContent=
"Tied game",document.getElementsByTagName("html")[0].style.backgroundColor="#c4fcc2",document.getElementById("board").style.backgroundColor="#36fc2f"):winner||(1===turn?(document.getElementsByTagName("html")[0].style.backgroundColor="#778899",document.getElementById("board").style.backgroundColor="#2196F3",document.getElementById("turn").textContent="Player 1's turn"):(document.getElementsByTagName("html")[0].style.backgroundColor="#aa8484",document.getElementById("board").style.backgroundColor="#f32121",
document.getElementById("turn").textContent="Player 2's turn"));document.getElementById("score").innerHTML="Player 1 wins: "+record.p1+"<br>Player 2 wins: "+record.p2+"<br>Ties: "+record.ties;if(winner){var a=document.createElement("div");a.id="start-buttons";var b=document.createElement("button");b.textContent="Play again!";b.setAttribute("onclick","reset();");a.appendChild(b);document.getElementById("turn").appendChild(a);saveRecord()}for(a=0;a<gameBoard.length;a++)for(b=0;b<gameBoard[a].length;b++){var c=
gameBoard.length*a+b;1===gameBoard[a][b]?(document.getElementById(c).textContent="X",document.getElementById(c).style.backgroundColor="#778899"):2===gameBoard[a][b]?(document.getElementById(c).textContent="O",document.getElementById(c).style.backgroundColor="#aa8484"):document.getElementById(c).textContent=""}},cellCheck=function(a){return gameBoard[a.row][a.column]},getCellCoords=function(a){updateCell({row:Math.floor(Number(a.target.id)/3),column:Math.floor(Number(a.target.id)%3)})},updateCell=
function(a){cellCheck(a)||winner||((gameBoard[a.row][a.column]=turn,checkWinner(),checkTie(),changeTurn(),refreshDisplay(),2!==mode||winner)?3!==mode||winner?4!==mode||winner||setTimeout(function(){play()},900):2===turn?modifyEventHandlers("getCellCoords(event)"):1===turn&&(modifyEventHandlers(""),setTimeout(function(){play()},1E3)):1===turn?modifyEventHandlers("getCellCoords(event)"):2===turn&&(modifyEventHandlers(""),setTimeout(function(){play()},1E3)))},checkWinner=function(){for(var a=[],b=[],
c=!0,g=!0,l=!0,e=!0,d=0;d<gameBoard.length;d++){for(var f=[],h=[],m=!0,n=!0,p=!0,q=!0,k=0;k<gameBoard[d].length;k++)f[f.length]=gameBoard[d][k],h[h.length]=gameBoard[k][d];for(k=0;k<gameBoard.length;k++)1!==f[k]&&(m=!1),1!==h[k]&&(n=!1),2!==f[k]&&(p=!1),2!==h[k]&&(q=!1);if(m||n)winner=1;else if(p||q)winner=2}for(d=0;d<gameBoard.length;d++)a[a.length]=gameBoard[d][d],b[b.length]=gameBoard[d][2-d];for(d=0;d<a.length;d++)1!==a[d]&&(c=!1),1!==b[d]&&(g=!1),2!==a[d]&&(l=!1),2!==b[d]&&(e=!1);if(c||g)winner=
1;else if(l||e)winner=2},checkTie=function(){for(var a=!0,b=0;b<gameBoard.length;b++)for(var c=0;c<gameBoard[b].length;c++)0===gameBoard[b][c]&&(a=!1);a&&!winner&&(winner=-1)},twoOutOfThree=function(a){return 1===cellCheck(a[0])&&1===cellCheck(a[1])?1:2===cellCheck(a[0])&&2===cellCheck(a[1])?2:1===cellCheck(a[0])&&2===cellCheck(a[1])||2===cellCheck(a[0])&&1===cellCheck(a[1])?-1:0},cellsInRow=function(a){for(var b=[{row:a.row,column:0},{row:a.row,column:1},{row:a.row,column:2}],c=0;c<b.length;c++)a.column===
b[c].column&&b.splice(c,1);return b},cellsInColumn=function(a){for(var b=[{row:0,column:a.column},{row:1,column:a.column},{row:2,column:a.column}],c=0;c<b.length;c++)a.row===b[c].row&&b.splice(c,1);return b},cellsInDiagA=function(a){for(var b=[{row:0,column:0},{row:1,column:1},{row:2,column:2}],c=0;c<b.length;c++)a.row===b[c].row&&b.splice(c,1);return b},cellsInDiagB=function(a){for(var b=[{row:0,column:2},{row:1,column:1},{row:2,column:0}],c=0;c<b.length;c++)a.row===b[c].row&&b.splice(c,1);return b},
play=function(){for(var a=[{score:2,valid:!1,diagA:!0,diagB:!1},{score:1,valid:!1,diagA:!1,diagB:!1},{score:2,valid:!1,diagA:!1,diagB:!0},{score:1,valid:!1,diagA:!1,diagB:!1},{score:2,valid:!1,diagA:!0,diagB:!0},{score:1,valid:!1,diagA:!1,diagB:!1},{score:2,valid:!1,diagA:!1,diagB:!0},{score:1,valid:!1,diagA:!1,diagB:!1},{score:2,valid:!1,diagA:!0,diagB:!1}],b=-Infinity,c=0,g=[],l={row:0,column:0},e=0;e<gameBoard.length;e++)for(var d=0;d<gameBoard[e].length;d++){var f=gameBoard.length*e+d,h={row:e,
column:d};if(0===gameBoard[e][d]){var m=cellsInRow(h),n=cellsInColumn(h);-1===twoOutOfThree(m)?--a[f].score:0!==twoOutOfThree(m)&&(a[f].score+=2);-1===twoOutOfThree(n)?--a[f].score:0!==twoOutOfThree(n)&&(a[f].score+=2);a[f].diagA&&(m=cellsInDiagA(h),-1===twoOutOfThree(m)?--a[f].score:0!==twoOutOfThree(m)&&(a[f].score+=2));a[f].diagB&&(h=cellsInDiagB(h),-1===twoOutOfThree(h)?--a[f].score:0!==twoOutOfThree(h)&&(a[f].score+=2));a[f].valid=!0}}0<turns&&(a[4].score=420);gameBoard[0][0]===gameBoard[2][2]&&
gameBoard[0][0]&&(a[1].score+=2,a[3].score+=2,a[5].score+=2,a[7].score+=2);gameBoard[0][2]===gameBoard[2][0]&&gameBoard[0][2]&&(a[1].score+=2,a[3].score+=2,a[5].score+=2,a[7].score+=2);for(e=0;e<a.length;e++)a[e].score>b&&a[e].valid?(b=a[e].score,c=e,g.length=0,g[g.length]=e):a[e].score===b&&a[e].valid&&(g[g.length]=e);1<g.length&&(c=g[Math.floor(Math.random()*g.length)]);l.row=Math.floor(c/3);l.column=c%3;updateCell(l)};loadRecord();